#!/bin/sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom &
dunst &
xfce4-power-manager --daemon
nm-applet &
thunar --daemon &
"$HOME"/.config/.fehbg &
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR"/keyring/ssh
